### ISSUE TITLE
Error when running ls with no snapshot

### ISSUE THREAD

**Issue by albatrossir** [albatrossir/albatrossir.github.io#9]
```
Traceback (most recent call last):
  File ".\command.py", line 535, in <module>
    Albatross().cmdloop()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File ".\command.py", line 503, in do_use
    i.cmdloop()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File ".\command.py", line 152, in do_ls
    dirs = data['dirs']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by albatrossir** [comment]
Fixed
